import { VoiceDNA } from '../types';

export const VOICE_DNA: Record<string, VoiceDNA> = {
  'NG': {
    countryId: 'NG',
    region: 'West Africa',
    capital: 'Abuja/Lagos',
    localLanguages: ['Hausa', 'Yoruba', 'Igbo', 'Pidgin English'],
    speechMelody: 'Dynamic, expressive, and highly melodic with varied pitch that emphasizes key nouns and verbs.',
    consonantStyle: 'Crisp and pronounced consonants. Hard "t" and "d" sounds, often vocalized with deep resonance.',
    rhythmPattern: 'Syllable-timed rather than stress-timed, giving it a staccato yet flowing and energetic rhythm.',
    culturalContext: 'Direct, confident, and persuasive. Rooted in oral storytelling and lively market interactions. Displays high energy and warmth.',
    antiPatterns: ['British RP English', 'Standard American English', 'Australian English', 'South African English'],
    defaultWarmth: 8,
    defaultConfidence: 9,
    defaultEnergy: 9
  },
  'CI': {
    countryId: 'CI',
    region: 'West Africa',
    capital: 'Abidjan',
    localLanguages: ['Baoulé', 'Dioula', 'Bété', 'Nouchi'],
    speechMelody: 'Musical, warm, and highly expressive. Uses rising intonations at the ends of phrases to invite agreement or show surprise.',
    consonantStyle: 'Softened "r" sounds (often rolled or tapped), distinct nasal vowels, and clearly articulated bilabials.',
    rhythmPattern: 'Bouncy and rhythmic. Syllables are often elongated for emphasis, especially in exclamations.',
    culturalContext: 'Joyful, convivial, and expressive. Heavily influenced by Nouchi (Ivorian slang) rhythm, creating a welcoming and engaged tone.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Standard European French'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'CM': {
    countryId: 'CM',
    region: 'Central Africa',
    capital: 'Yaoundé/Douala',
    localLanguages: ['Ewondo', 'Duala', 'Fulfulde', 'Camfranglais'],
    speechMelody: 'Deep, resonant, and authoritative. Often features a robust and grounded pitch with deliberate pauses.',
    consonantStyle: 'Strong, percussive consonants. Distinct articulation of plosives (p, b, t, d, k, g).',
    rhythmPattern: 'Measured and deliberate, carrying a heavy, confident cadence. Evenly spaced syllables with powerful stress on action words.',
    culturalContext: 'Assertive, serious, and deeply grounded. The tone conveys authority, respect, and a no-nonsense attitude.',
    antiPatterns: ['Parisian French', 'Standard European French', 'West African French (Senegalese style)'],
    defaultWarmth: 6,
    defaultConfidence: 9,
    defaultEnergy: 7
  },
  'SN': {
    countryId: 'SN',
    region: 'West Africa',
    capital: 'Dakar',
    localLanguages: ['Wolof', 'Pulaar', 'Jola'],
    speechMelody: 'Smooth, fluid, and polite. Features gentle cascading intonations, especially in greetings and storytelling.',
    consonantStyle: 'Softer consonants, distinct Wolof-influenced vowels, and lightly tapped "r" sounds.',
    rhythmPattern: 'Flowing and continuous. Sentences often run together with a smooth, poetic cadence.',
    culturalContext: 'Rooted in "Teranga" (hospitality). The speech is respectful, calm, dignified, and extremely hospitable.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Aggressive or rushed speech'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'CD': {
    countryId: 'CD',
    region: 'Central Africa',
    capital: 'Kinshasa',
    localLanguages: ['Lingala', 'Swahili', 'Tshiluba', 'Kikongo'],
    speechMelody: 'Extremely melodic, musical, and vibrant. Pitch fluctuates gracefully, heavily influenced by the tonality of Lingala.',
    consonantStyle: 'Soft, rounded consonants. Vowels are open, bright, and clearly sustained.',
    rhythmPattern: 'Lively, dance-like rhythm. Features rhythmic syncopation and frequent use of expressive interjections.',
    culturalContext: 'Highly sociable, artistic, and dramatic. The voice is flamboyant, engaging, and designed to captivate an audience.',
    antiPatterns: ['Parisian French', 'Belgian French', 'Monotone delivery'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  'GH': {
    countryId: 'GH',
    region: 'West Africa',
    capital: 'Accra',
    localLanguages: ['Twi', 'Ga', 'Ewe', 'Fante'],
    speechMelody: 'Polite, lilting, and respectful. Pitch often rises gently at the end of sentences.',
    consonantStyle: 'Clear, crisp consonants. The "r" is often pronounced distinctly, and vowels have a full, round quality.',
    rhythmPattern: 'Measured, steady, and clear. Sentences are paced deliberately for maximum clarity and respect.',
    culturalContext: 'Dignified, courteous, and warm. Speech conveys respect for elders and guests, highly focused on clear communication.',
    antiPatterns: ['Standard American English', 'British RP English', 'Nigerian English (too aggressive)'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  'MA': {
    countryId: 'MA',
    region: 'North Africa',
    capital: 'Casablanca/Rabat',
    localLanguages: ['Darija', 'Tamazight'],
    speechMelody: 'Fast-paced, intricate, and undulating. Blends the rhythmic structure of Arabic with French vocabulary seamlessly.',
    consonantStyle: 'Guttural and emphatic consonants (kha, qaf). Deeply resonant throat sounds mixed with crisp French articulation.',
    rhythmPattern: 'Staccato bursts followed by flowing phrases. Highly dynamic pacing that adapts to the emotion of the speaker.',
    culturalContext: 'Expressive, hospitable, and sharp. Reflects a crossroads of Mediterranean, African, and Middle Eastern cultures.',
    antiPatterns: ['Parisian French', 'Levantine Arabic', 'Gulf Arabic'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'ZA': {
    countryId: 'ZA',
    region: 'Southern Africa',
    capital: 'Johannesburg',
    localLanguages: ['Zulu', 'Xhosa', 'Afrikaans', 'Sotho'],
    speechMelody: 'Broad, resonant, and dynamic. Vowel sounds are often shifted or stretched, giving it a distinct color.',
    consonantStyle: 'Crisp articulation of "t" and "k". Occasional glottal stops and distinct clipping of certain syllables.',
    rhythmPattern: 'Punchy and clear. Can switch between a laid-back drawl and rapid, energetic bursts depending on context.',
    culturalContext: 'Direct, confident, and diverse. A melting pot of accents reflecting a complex, modern, and vibrant society.',
    antiPatterns: ['British RP English', 'Australian English', 'Standard American English'],
    defaultWarmth: 7,
    defaultConfidence: 9,
    defaultEnergy: 8
  },
  'KE': {
    countryId: 'KE',
    region: 'East Africa',
    capital: 'Nairobi',
    localLanguages: ['Swahili', 'Kikuyu', 'Luo', 'Sheng'],
    speechMelody: 'Bright, rhythmic, and engaging. Intonation often emphasizes the penultimate syllable, drawn from Swahili influence.',
    consonantStyle: 'Clear, strong consonants. The "r" is rolled, and vowels are pure and un-diphthongized.',
    rhythmPattern: 'Steady, staccato rhythm. Highly syllable-timed, making the speech sound clear, punchy, and upbeat.',
    culturalContext: 'Polite but energetic, entrepreneurial, and community-focused. Very clean and precise enunciation.',
    antiPatterns: ['Standard American English', 'British RP English', 'West African English'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'GA': {
    countryId: 'GA',
    region: 'Central Africa',
    capital: 'Libreville',
    localLanguages: ['Fang', 'Myene', 'Nzebi'],
    speechMelody: 'Smooth, relaxed, and polished. Pitch is relatively flat compared to West African French, with a sophisticated tone.',
    consonantStyle: 'Soft articulation, heavily influenced by local Bantu languages. Vowels are open but controlled.',
    rhythmPattern: 'Fluid, unhurried, and continuous. Sentences glide effortlessly with minimal harsh pauses.',
    culturalContext: 'Elegant, calm, and grounded. Represents a lush, equatorial lifestyle with a refined urban center.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Standard European French', 'American English', 'British English'],
    defaultWarmth: 7,
    defaultConfidence: 8,
    defaultEnergy: 6
  },
  'BJ': {
    countryId: 'BJ',
    region: 'West Africa',
    capital: 'Cotonou',
    localLanguages: ['Fon', 'Yoruba', 'Bariba'],
    speechMelody: 'Warm, resonant, and expressive. Tonality is heavily influenced by tonal languages like Fon and Yoruba.',
    consonantStyle: 'Deep, throaty consonants. Vowels are expansive, and nasal sounds are heavily utilized.',
    rhythmPattern: 'Rhythmic and deliberate. Emphasizes emotional connection and often employs dramatic pauses.',
    culturalContext: 'Deeply traditional, respectful, and spirited. Rooted in rich cultural history and animated storytelling.',
    antiPatterns: ['Parisian French', 'European French', 'Monotone delivery'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  'BF': {
    countryId: 'BF',
    region: 'West Africa',
    capital: 'Ouagadougou',
    localLanguages: ['Mooré', 'Dioula', 'Fulfulde'],
    speechMelody: 'Grounded, sincere, and steadfast. Intonation is relatively steady, conveying honesty and directness.',
    consonantStyle: 'Strong, forceful consonants. Clear and unpretentious articulation.',
    rhythmPattern: 'Even, marching rhythm. Speech is paced to ensure absolute clarity and understanding.',
    culturalContext: 'Known as the "Land of Honest Men." The tone is earnest, hardworking, proud, and deeply sincere.',
    antiPatterns: ['Parisian French', 'Overly dramatic speech', 'Fast-paced metropolitan accents'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  'ML': {
    countryId: 'ML',
    region: 'West Africa',
    capital: 'Bamako',
    localLanguages: ['Bambara', 'Songhai', 'Tamasheq'],
    speechMelody: 'Poetic, flowing, and deeply musical. Intonation reflects the rich tradition of the Griots (storytellers).',
    consonantStyle: 'Softened consonants, melodious vowels, and a distinct Bambara lilt.',
    rhythmPattern: 'Fluid and cascading. Sentences are structured like musical phrases with a gentle ebb and flow.',
    culturalContext: 'Reverent, artistic, and historical. Speech is used as a tool for connection, diplomacy, and artistry.',
    antiPatterns: ['Parisian French', 'Aggressive or harsh tones', 'Staccato rhythms'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'TG': {
    countryId: 'TG',
    region: 'West Africa',
    capital: 'Lomé',
    localLanguages: ['Ewe', 'Kabiye'],
    speechMelody: 'Friendly, bright, and inviting. The pitch often modulates to show empathy and interest.',
    consonantStyle: 'Clear, crisp consonants with a distinctive Ewe influence on the vowels.',
    rhythmPattern: 'Upbeat and bouncy. Conversations have a lively back-and-forth dynamic.',
    culturalContext: 'Welcoming, warm, and communal. The voice reflects a tight-knit community and a relaxed coastal lifestyle.',
    antiPatterns: ['Parisian French', 'Cold, distant tones'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  'CG': {
    countryId: 'CG',
    region: 'Central Africa',
    capital: 'Brazzaville',
    localLanguages: ['Kikongo', 'Lingala'],
    speechMelody: 'Sophisticated, melodic, and smooth. Often described as elegant and stylized.',
    consonantStyle: 'Soft, well-rounded articulation. A distinct flair in the pronunciation of French words.',
    rhythmPattern: 'Graceful and measured. Avoids harsh stops, preferring a continuous, velvety flow.',
    culturalContext: 'Known for the "Sapeur" culture—highly stylized, proud, elegant, and fashionable in both dress and speech.',
    antiPatterns: ['Parisian French', 'Standard European French', 'Unrefined or raw delivery'],
    defaultWarmth: 7,
    defaultConfidence: 9,
    defaultEnergy: 7
  },
  'TN': {
    countryId: 'TN',
    region: 'North Africa',
    capital: 'Tunis',
    localLanguages: ['Tunisian Arabic (Derja)'],
    speechMelody: 'Bright, melodic, and fast-paced. Intonation sweeps up and down quickly, reflecting a blend of Arabic and Mediterranean influences.',
    consonantStyle: 'Crisp, forward consonants. Guttural Arabic sounds are smoothed out compared to other regional dialects.',
    rhythmPattern: 'Rapid, energetic, and staccato. Highly expressive and often accompanied by animated gestures.',
    culturalContext: 'Modern, Mediterranean, and vibrant. Speech is outgoing, sociable, and culturally fluid.',
    antiPatterns: ['Parisian French', 'Gulf Arabic', 'Levantine Arabic'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  'DZ': {
    countryId: 'DZ',
    region: 'North Africa',
    capital: 'Alger',
    localLanguages: ['Darja', 'Tamazight'],
    speechMelody: 'Strong, assertive, and passionate. Pitch drops at the end of sentences for emphasis and authority.',
    consonantStyle: 'Heavy, guttural consonants. French words are often pronounced with hard Arabic inflection.',
    rhythmPattern: 'Powerful and punctuated. Rhythmic bursts of intense emotion followed by deliberate pauses.',
    culturalContext: 'Proud, fiery, and deeply independent. The voice commands respect and conveys strong emotion.',
    antiPatterns: ['Parisian French', 'Soft or timid delivery', 'Middle Eastern Arabic'],
    defaultWarmth: 6,
    defaultConfidence: 10,
    defaultEnergy: 9
  },
  'EG': {
    countryId: 'EG',
    region: 'North Africa',
    capital: 'Le Caire',
    localLanguages: ['Egyptian Arabic'],
    speechMelody: 'Highly expressive, warm, and theatrical. Famous across the Arab world for its distinct, melodic drawl.',
    consonantStyle: 'Pronounces the "j" as a hard "g". Vowels are elongated, and articulation is broad and relaxed.',
    rhythmPattern: 'Flowing, rhythmic, and often humorous. The pacing is designed to entertain and engage the listener.',
    culturalContext: 'Charming, dramatic, and deeply rooted in cinema and media. The voice is universally recognizable, persuasive, and warm.',
    antiPatterns: ['Standard American English', 'Levantine Arabic', 'Gulf Arabic'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'UG': {
    countryId: 'UG',
    region: 'East Africa',
    capital: 'Kampala',
    localLanguages: ['Luganda', 'Swahili', 'Runyankore'],
    speechMelody: 'Extremely polite, melodic, and gentle. Luganda tonal influence creates a distinctive sing-song quality.',
    consonantStyle: 'Soft consonants, often avoiding harsh plosives. Vowels are highly emphasized and extended.',
    rhythmPattern: 'Smooth, unhurried, and continuous. Avoids abrupt stops, flowing gently from one word to the next.',
    culturalContext: 'Renowned for extreme politeness and hospitality. Speech is warm, accommodating, and deeply respectful.',
    antiPatterns: ['Standard American English', 'British RP English', 'Aggressive or harsh delivery'],
    defaultWarmth: 10,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'TZ': {
    countryId: 'TZ',
    region: 'East Africa',
    capital: 'Dar es Salaam',
    localLanguages: ['Swahili'],
    speechMelody: 'Smooth, deeply resonant, and grounded. Swahili is the core, giving a beautiful, rolling cadence.',
    consonantStyle: 'Clear, pure vowels. Consonants are articulated cleanly but softly, without hard edges.',
    rhythmPattern: 'Steady, relaxed, and rhythmic. It carries a calm, unhurried coastal vibe (Bongo Flava influence).',
    culturalContext: 'Peaceful, unified, and proud. Swahili is the great unifier, and the speech reflects a calm, collective identity.',
    antiPatterns: ['Standard American English', 'British RP English', 'Fast-paced, stressful rhythms'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  }
};
