// ──────────────────────────────────────────────────────────────
// Voice DNA Database & Local Expressions (19 African Countries)
// Unified Source of Truth for Server, Serverless, and Client
// ──────────────────────────────────────────────────────────────

export const VOICE_DNA = {
  NG: {
    countryId: 'NG',
    region: 'West Africa',
    capital: 'Abuja/Lagos',
    localLanguages: ['Hausa', 'Yoruba', 'Igbo', 'Pidgin English'],
    speechMelody: 'Highly melodic and dynamic Nigerian intonation. Pitch rises vibrantly on key nouns and action verbs, carrying a commanding yet warm cadence. Stress shifts to emphasize action phrases (e.g. chaLLENGE instead of CHAllenge).',
    consonantStyle: 'Crisp, firm, and percussive consonants. Hard "t" and "d" sounds substituting for dental fricatives ("thing" sounds like "ting", "them" like "dem"). Deep pectoral resonance with clear bilabial articulation.',
    rhythmPattern: 'Syllable-timed, punchy staccato rhythm with rapid, confident delivery. Monophthongized vowels (diphthongs like "goat" become pure [got], "face" becomes [fes]).',
    culturalContext: 'Extremely confident, charismatic, direct, and persuasive. Inspired by Lagos urban energy, Naija pride, and rich oral traditions.',
    antiPatterns: ['British RP English', 'Standard American English', 'Australian English', 'South African English', 'Monotone robotic TTS'],
    defaultWarmth: 8,
    defaultConfidence: 9,
    defaultEnergy: 9
  },
  CI: {
    countryId: 'CI',
    region: 'West Africa',
    capital: 'Abidjan',
    localLanguages: ['Baoulé', 'Dioula', 'Bété', 'Nouchi'],
    speechMelody: 'Warm, musical, and highly expressive Ivorian lilt. Phrases naturally end with a gentle rising intonation (Nouchi vibe) that invites warmth and connection.',
    consonantStyle: 'Softened tapped or silent "r" sounds, rich open nasal vowels (an, on, in), clear bilabials, and smooth consonant transitions.',
    rhythmPattern: 'Bouncy, syncopated, and rhythmic. Key vowels are slightly elongated for emphasis, reflecting Abidjan Nouchi speech cadence. Omission of definite articles replaced by suffix "-là" (e.g. "chapeau-là").',
    culturalContext: 'Joyful, hospitable, convivial, and deeply expressive. Captures the vibrant, welcoming street spirit of Abidjan.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Standard European French', 'Monotone delivery'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  CM: {
    countryId: 'CM',
    region: 'Central Africa',
    capital: 'Yaoundé/Douala',
    localLanguages: ['Ewondo', 'Duala', 'Fulfulde', 'Camfranglais'],
    speechMelody: 'Deep, authoritative, and grounded pitch. Heavy chest resonance with deliberate downward intonations at sentence endings. Pronounced tonic accent on final syllables.',
    consonantStyle: 'Strong, percussive consonants. Distinct, un-softened plosives (p, b, t, d, k, g) articulated with clear firmness. Heavily pronounced alveolar or uvular "r".',
    rhythmPattern: 'Measured, steady, and deliberate pacing with powerful, even stress across words conveying gravitas.',
    culturalContext: 'Assertive, serious, respectful, and dignified. Represents Cameroonian pride, authority, and calm strength.',
    antiPatterns: ['Parisian French', 'European French', 'Senegalese French', 'High-pitched rushed speech'],
    defaultWarmth: 6,
    defaultConfidence: 9,
    defaultEnergy: 7
  },
  SN: {
    countryId: 'SN',
    region: 'West Africa',
    capital: 'Dakar',
    localLanguages: ['Wolof', 'Pulaar', 'Jola'],
    speechMelody: 'Smooth, poetic, and fluid intonation. Features gentle cascading pitch transitions with polite, dignified vocal contours. Wolof-influenced undulating curves.',
    consonantStyle: 'Soft, clean consonants with distinct Wolof-influenced open vowels. Vowels /e/ and /ɛ/ merge (e.g., "lait" and "les" sound identical). Lightly tapped palatal sounds and distinct nasal vowels with a soft final consonant appendix.',
    rhythmPattern: 'Continuous, elegant, and lyrical flow. Sentences glide effortlessly with harmonious breathing pauses. Calm, hospitable pacing.',
    culturalContext: 'Infused with "Teranga" (world-famous Senegalese hospitality). Respectful, serene, noble, and deeply welcoming.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Harsh staccato', 'Aggressive delivery'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  CG: {
    countryId: 'CG',
    region: 'Central Africa',
    capital: 'Brazzaville / Kinshasa',
    localLanguages: ['Lingala', 'Kikongo', 'Tshiluba', 'Swahili'],
    speechMelody: 'Vibrant, highly melodious, and singing intonation. Pitch moves in graceful tonal arches shaped by Lingala musicality, with prolonged high tones on key vowels.',
    consonantStyle: 'Soft, rounded consonants with open, bright, sustained vowels and smooth vocalic resonance. Diphthongs are fully and clearly articulated.',
    rhythmPattern: 'Lively, dance-like, syncopated cadence with rhythmic pauses, expressive vocal warmth, and high musical energy.',
    culturalContext: 'Flamboyant, artistic, warm, and captivating. Reflects Congolese legendary music, Sapeur elegance, and vibrant cultural energy.',
    antiPatterns: ['Parisian French', 'Belgian French', 'Flat monotone delivery', 'Dull robotic speech'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  GH: {
    countryId: 'GH',
    region: 'West Africa',
    capital: 'Accra',
    localLanguages: ['Twi', 'Ga', 'Ewe', 'Fante'],
    speechMelody: 'Polite, melodic, and dignified pitch contour with gentle rising inflections drawn from Twi tonal patterns. Balanced and respectful.',
    consonantStyle: 'Crisp, clean, articulate consonants with full, rounded vowels. Dental fricatives ("th") become /t/ or /d/. Clear enunciation including spelling-based pronunciations (like pronouncing the "b" in "climb").',
    rhythmPattern: 'Measured, steady, and clear. Balanced syllable-timing designed for maximum clarity, respect, and storytelling pacing.',
    culturalContext: 'Warm, courteous, educated, and hospitable. Reflects Ghanaian royal dignity, polite demeanor, and respectful storytelling.',
    antiPatterns: ['Standard American English', 'British RP English', 'Harsh aggressive delivery'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  MA: {
    countryId: 'MA',
    region: 'North Africa',
    capital: 'Casablanca/Rabat',
    localLanguages: ['Darija', 'Tamazight'],
    speechMelody: 'Fast, intricate, undulating melody blending Moroccan Arabic (Darija) vocal contours with precise French phrasing. Dynamic and lively.',
    consonantStyle: 'Rich guttural and pharyngeal resonance (/kh/, /q/, /h/) combined with crisp, forward bilabial articulation and trilled r (/r/).',
    rhythmPattern: 'Dynamic contrast between swift staccato word bursts and smooth, elegant sentence transitions.',
    culturalContext: 'Sophisticated, warm, sharp, and cosmopolitan. Reflects North African Maghrebi heritage and Mediterranean flair.',
    antiPatterns: ['Parisian French', 'Levantine Arabic', 'Gulf Arabic', 'Flat European delivery'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  ZA: {
    countryId: 'ZA',
    region: 'Southern Africa',
    capital: 'Johannesburg',
    localLanguages: ['Zulu', 'Xhosa', 'Afrikaans', 'Sotho'],
    speechMelody: 'Broad, resonant, open vocal melody. Rich back-of-throat resonance with dynamic pitch variations and Zulu-influenced cadence.',
    consonantStyle: 'Crisp, sharp articulation of "t" and "k", subtle glottal stops, and firm consonant releases. Tapped or rolled "r". Vowel split (e.g. kit vs bit).',
    rhythmPattern: 'Punchy, energetic, and rhythmic with smooth transitions between deliberate emphasis and rapid bursts. Syllable-timed.',
    culturalContext: 'Bold, modern, confident, and direct. Grounded in Ubuntu spirit, urban vibrancy, and raw authenticity.',
    antiPatterns: ['British RP English', 'Australian English', 'Standard American English', 'Robotic TTS'],
    defaultWarmth: 7,
    defaultConfidence: 9,
    defaultEnergy: 8
  },
  KE: {
    countryId: 'KE',
    region: 'East Africa',
    capital: 'Nairobi',
    localLanguages: ['Swahili', 'Kikuyu', 'Luo', 'Sheng'],
    speechMelody: 'Bright, rhythmic, and upbeat intonation. Strong emphasis on penultimate syllables (second-to-last syllable of words) following Swahili speech rules.',
    consonantStyle: 'Clear, strong consonants with rolled or tapped "r". Vowel inventory reduced to 5 pure Swahili vowels [i, e, a, o, u] without length distinction (feet/fit sound identical).',
    rhythmPattern: 'Steady, punchy, syllable-timed staccato rhythm with crisp, energetic transitions and polite, clear enunciation.',
    culturalContext: 'Entrepreneurial, articulate, polite, and forward-looking. Nairobi tech-hub energy with East African Swahili clarity.',
    antiPatterns: ['Standard American English', 'British RP English', 'West African Pidgin'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  GA: {
    countryId: 'GA',
    region: 'Central Africa',
    capital: 'Libreville',
    localLanguages: ['Fang', 'Myene', 'Nzebi'],
    speechMelody: 'Smooth, relaxed, refined, and sophisticated. Controlled pitch contour with subtle equatorial elegance and rhythmic rises at the end of groups.',
    consonantStyle: 'Soft, rounded Bantu-influenced consonant articulation with polished, open French vowels. Gentle tapped "r".',
    rhythmPattern: 'Fluid, unhurried, and continuous pacing where sentences flow effortlessly without abrupt stops.',
    culturalContext: 'Calm, cultivated, diplomatic, and noble. Reflects equatorial forest heritage and Libreville refinement.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Harsh European French'],
    defaultWarmth: 7,
    defaultConfidence: 8,
    defaultEnergy: 6
  },
  BJ: {
    countryId: 'BJ',
    region: 'West Africa',
    capital: 'Cotonou',
    localLanguages: ['Fon', 'Yoruba', 'Bariba'],
    speechMelody: 'Warm, resonant, narrative intonation shaped by Fon tonal pitch movements and expressive inflection.',
    consonantStyle: 'Deep, chesty consonant resonance with expansive, clear, and very open nasal vowels and nasal harmony. Firm plosives.',
    rhythmPattern: 'Deliberate, storytelling-oriented rhythm with meaningful artistic pauses. Highly expressive.',
    culturalContext: 'Deeply traditional, respectful, spirited, and historical. Rooted in ancient Dahomey oral art.',
    antiPatterns: ['Parisian French', 'European French', 'Monotone delivery'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  BF: {
    countryId: 'BF',
    region: 'West Africa',
    capital: 'Ouagadougou',
    localLanguages: ['Mooré', 'Dioula', 'Fulfulde'],
    speechMelody: 'Grounded, sincere, steady pitch contour conveying deep honesty, integrity, and direct connection. Respectful cadence.',
    consonantStyle: 'Strong, clear, unpretentious consonants derived from Mooré phonetic strength. Neutral vowels.',
    rhythmPattern: 'Even, march-like steady rhythm paced deliberately for absolute understanding and calm pacing.',
    culturalContext: 'Proud, earnest, and deeply sincere — representing the "Land of Upright People".',
    antiPatterns: ['Parisian French', 'Overly dramatic speech', 'Rushed urban French'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  ML: {
    countryId: 'ML',
    region: 'West Africa',
    capital: 'Bamako',
    localLanguages: ['Bambara', 'Songhai', 'Tamasheq'],
    speechMelody: 'Poetic, flowing, deeply musical Griot melody. Intonation ebbs and flows like ancestral storytelling. Smooth and undulating.',
    consonantStyle: 'Softened, melodious consonants with rich Bambara vowel lilt and warm resonance. Deep chest tones.',
    rhythmPattern: 'Fluid, cascading cadence structured like musical storytelling phrases. Unhurried and noble.',
    culturalContext: 'Reverent, historic, artistic, and peaceful. The voice is a noble instrument of wisdom and history.',
    antiPatterns: ['Parisian French', 'Harsh aggressive tones', 'Rapid staccato'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  TG: {
    countryId: 'TG',
    region: 'West Africa',
    capital: 'Lomé',
    localLanguages: ['Ewe', 'Kabiye'],
    speechMelody: 'Friendly, bright, inviting pitch modulation that shows high empathy and warmth. Light rising pitches at sentence endings.',
    consonantStyle: 'Clear, crisp consonants with distinct Ewe/Mina vowel coloring and gentle articulation. Bright open vowels.',
    rhythmPattern: 'Upbeat, bouncy, lively rhythm reflecting coastal Lomé warmth. Rapid delivery.',
    culturalContext: 'Welcoming, relaxed, communal, and genuine. Coastal Lomé warmth and community connection.',
    antiPatterns: ['Parisian French', 'Cold distant European tone'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  TN: {
    countryId: 'TN',
    region: 'North Africa',
    capital: 'Tunis',
    localLanguages: ['Tunisian Derja'],
    speechMelody: 'Bright, agile, Mediterranean melody. Quick pitch inflections blending Derja and French cadences. Soft gutturals.',
    consonantStyle: 'Crisp, forward consonants with smoothed guttural sounds and clear open vowels.',
    rhythmPattern: 'Rapid, energetic, staccato rhythm filled with expressive Mediterranean vitality.',
    culturalContext: 'Cosmopolitan, warm, scholarly, and vibrant Mediterranean North African voice.',
    antiPatterns: ['Parisian French', 'Gulf Arabic', 'Levantine Arabic'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  DZ: {
    countryId: 'DZ',
    region: 'North Africa',
    capital: 'Alger',
    localLanguages: ['Darja', 'Tamazight'],
    speechMelody: 'Bold, assertive, passionate intonation with strong emphasis and decisive pitch drops at sentence ends.',
    consonantStyle: 'Heavy, guttural Arabic consonant depth (kh, q) infusing French words with authentic Maghrebi power. Intense plosives.',
    rhythmPattern: 'Punctuated, rhythmic bursts of passionate delivery followed by intentional dramatic pauses.',
    culturalContext: 'Fiery, proud, independent, and commanding. A voice of dignity, strength, and Maghrebi pride.',
    antiPatterns: ['Parisian French', 'Timid weak delivery', 'Middle Eastern Arabic'],
    defaultWarmth: 6,
    defaultConfidence: 10,
    defaultEnergy: 9
  },
  EG: {
    countryId: 'EG',
    region: 'North Africa',
    capital: 'Le Caire',
    localLanguages: ['Egyptian Arabic'],
    speechMelody: 'Theatrical, warm, iconic Cairo melody. Richly expressive pitch drawl recognized across the region. High dramatic value.',
    consonantStyle: 'Hard "g" for "j" (e.g. job -> gob). Elongated vowels, broad, relaxed, cinematic articulation. Dental fricatives become /s/, /z/, /t/ or /d/.',
    rhythmPattern: 'Flowing, rhythmic, engaging, and cinematic with natural dramatic pauses.',
    culturalContext: 'Charming, dramatic, master-storyteller energy rooted in Egyptian film and broadcast legacy.',
    antiPatterns: ['Standard American English', 'Levantine Arabic', 'Gulf Arabic'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  UG: {
    countryId: 'UG',
    region: 'East Africa',
    capital: 'Kampala',
    localLanguages: ['Luganda', 'Swahili', 'Runyankore'],
    speechMelody: 'Gentle, sing-song Luganda melody. Soft pitch modulation carrying profound warmth and extreme politeness.',
    consonantStyle: 'Soft consonants avoiding harsh plosives, paired with extended, melodic vowels.',
    rhythmPattern: 'Smooth, unhurried, continuous flow with gentle transitions between phrases. Syllable-timed.',
    culturalContext: 'Pearl of Africa identity — famed for extreme politeness, warmth, and respectful grace.',
    antiPatterns: ['Standard American English', 'British RP English', 'Aggressive delivery'],
    defaultWarmth: 10,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  TZ: {
    countryId: 'TZ',
    region: 'East Africa',
    capital: 'Dar es Salaam',
    localLanguages: ['Swahili'],
    speechMelody: 'Deeply resonant, pure Swahili rolling melody. Peaceful, grounded, and harmonious pitch contour.',
    consonantStyle: 'Clean, soft Bantu articulation with unblemished, pure open vowels. Non-rhotic, soft dentals.',
    rhythmPattern: 'Relaxed, steady, rhythmic coastal cadence (Bongo Flava peace and tranquility). Polite, measured delivery.',
    culturalContext: 'Peaceful, unified, harmonious Swahili identity — warm, inclusive, and grounded.',
    antiPatterns: ['Standard American English', 'British RP English', 'Rushed stressful cadence'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  }
};

export const LOCAL_EXPRESSIONS = {
  NG: {
    fillers: ['you know', 'abeg', 'my brother', 'my sister', 'ehn'],
    greetings: ['How far?', 'How body?', 'Wetin dey?'],
    emphasis: ['I swear!', 'Na so!', 'Na wa o!'],
  },
  CI: {
    fillers: ['dêh', 'wôrô-wôrô', 'kpakpatoya', 'on dit quoi', 'mogo'],
    greetings: ['Ça va ou bien?', 'C\'est comment?'],
    emphasis: ['C\'est chaud!', 'Walahi!', 'Dja!'],
  },
  CM: {
    fillers: ['c\'est ça même', 'je dis seulement', 'tu vois non', 'massah'],
    greetings: ['Wèè!', 'C\'est comment?'],
    emphasis: ['Aïe!', 'Tu vois!', 'Mon frère!'],
  },
  SN: {
    fillers: ['ndéysan', 'dégal', 'waaw', 'voilà'],
    greetings: ['Salaam aleekum', 'Na nga def?'],
    emphasis: ['Yalla!', 'Inchallah!', 'Machallah!'],
  },
  CG: {
    fillers: ['pona nini', 'yo', 'eloko', 'pesa', 'lokola'],
    greetings: ['Mbote na yo!', 'Oza bien?'],
    emphasis: ['Tozali!', 'Eh eh!', 'Mawa!', 'C\'est fort!'],
  },
  GH: {
    fillers: ['chale', 'as for me', 'you see', 'charley'],
    greetings: ['Ete sen?', 'Wo ho te sen?'],
    emphasis: ['Charley!', 'Herh!', 'Ei!'],
  },
  MA: {
    fillers: ['walakin', 'yak', 'safi', 'a khoya'],
    greetings: ['Labas?', 'Kif dayr?'],
    emphasis: ['Wallah!', 'Bismillah!', 'Wakha!'],
  },
  ZA: {
    fillers: ['shame', 'just now', 'hey man', 'bra'],
    greetings: ['Howzit?', 'Aweh!'],
    emphasis: ['Eish!', 'Haibo!', 'Yoh!'],
  },
  KE: {
    fillers: ['si you know', 'ati', 'lakini', 'bana'],
    greetings: ['Sasa!', 'Mambo vipi?'],
    emphasis: ['Aki!', 'Kweli!', 'Basi!'],
  },
  GA: {
    fillers: ['disons', 'non mais', 'voilà quoi', 'yaye'],
    greetings: ['Mbolo!', 'Tu vas?'],
    emphasis: ['Ah bon?', 'C\'est sérieux!', 'C\'est chaud!'],
  },
  BJ: {
    fillers: ['kpèkpè', 'à côté de ça', 'voilà', 'enfin'],
    greetings: ['A fon gbé?', 'Kudo?'],
    emphasis: ['Azô!', 'Ah bon!', 'Yoo!'],
  },
  BF: {
    fillers: ['bon', 'ça va aller', 'en tout cas'],
    greetings: ['Laafi?', 'Bala?'],
    emphasis: ['Inch\'Allah!', 'C\'est sûr!', 'Walahi!'],
  },
  ML: {
    fillers: ['bon', 'voilà', 'barika'],
    greetings: ['I ni sogoma!', 'I ni ce!'],
    emphasis: ['Wallahi!', 'Barika!', 'Mogoya!'],
  },
  TG: {
    fillers: ['éfè', 'bon', 'n\'est-ce pas', 'fo'],
    greetings: ['Efoa?', 'Ndi!'],
    emphasis: ['Yoo!', 'Ah!', 'Ah bon!'],
  },
  TN: {
    fillers: ['barcha', 'ya3ni', 'voilà', 'ey'],
    greetings: ['Chnahwelek?', 'Labès?'],
    emphasis: ['Wallahi!', 'Ya hasra!', 'Inchallah!'],
  },
  DZ: {
    fillers: ['bezaf', 'saha', 'wach', 'khoya'],
    greetings: ['Wach rak?', 'Saha!'],
    emphasis: ['Wallah!', 'Ya Rebbi!', 'Saha!'],
  },
  EG: {
    fillers: ['ya3ni', 'tab3an', 'ma3lesh', 'khalas'],
    greetings: ['Ezzayak?', 'Ahlan wa sahlan!'],
    emphasis: ['Wallahi!', 'Ya Salam!', 'Yalla!'],
  },
  UG: {
    fillers: ['banange', 'actually', 'you see', 'kali'],
    greetings: ['Oli otya?', 'Gyendi!'],
    emphasis: ['Bambi!', 'Banange!', 'Webale!'],
  },
  TZ: {
    fillers: ['sawa sawa', 'kweli', 'basi'],
    greetings: ['Habari!', 'Mambo!'],
    emphasis: ['Kweli!', 'Pole sana!', 'Asante!'],
  },
};
