import { VoiceProfile } from '../types';

export const VOICE_PROFILES: Record<string, VoiceProfile> = {
  // 🇸🇳 SÉNÉGAL
  SENEGAL_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'SENEGAL_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Senegal',
    language: 'French',
    gender: 'female',
    persona: 'Fatou',
    masterVoiceSample: 'services/voice-profiles/senegal/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/senegal/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.SENEGAL_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Senegal',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  SENEGAL_INFLUENCER_MALE_01: {
    voiceProfileId: 'SENEGAL_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Senegal',
    language: 'French',
    gender: 'male',
    persona: 'Babacar',
    masterVoiceSample: 'services/voice-profiles/senegal/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/senegal/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.SENEGAL_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Senegal',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇨🇮 CÔTE D'IVOIRE
  COTE_D_IVOIRE_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'COTE_D_IVOIRE_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: "Côte d'Ivoire",
    language: 'French',
    gender: 'female',
    persona: 'Aminata',
    masterVoiceSample: 'services/voice-profiles/cote-d-ivoire/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/cote-d-ivoire/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.COTE_D_IVOIRE_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: "Côte d'Ivoire",
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  COTE_D_IVOIRE_INFLUENCER_MALE_01: {
    voiceProfileId: 'COTE_D_IVOIRE_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: "Côte d'Ivoire",
    language: 'French',
    gender: 'male',
    persona: 'Kouassi',
    masterVoiceSample: 'services/voice-profiles/cote-d-ivoire/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/cote-d-ivoire/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.COTE_D_IVOIRE_INFLUENCER_MALE_01_KEY || '',
    accentProfile: "Côte d'Ivoire",
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇳🇬 NIGERIA
  NIGERIA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'NIGERIA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Nigeria',
    language: 'English',
    gender: 'female',
    persona: 'Blessing',
    masterVoiceSample: 'services/voice-profiles/nigeria/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/nigeria/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.NIGERIA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Nigeria',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  NIGERIA_INFLUENCER_MALE_01: {
    voiceProfileId: 'NIGERIA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Nigeria',
    language: 'English',
    gender: 'male',
    persona: 'Emeka',
    masterVoiceSample: 'services/voice-profiles/nigeria/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/nigeria/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.NIGERIA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Nigeria',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇨🇲 CAMEROUN
  CAMEROON_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'CAMEROON_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Cameroun',
    language: 'French',
    gender: 'female',
    persona: 'Chantal',
    masterVoiceSample: 'services/voice-profiles/cameroun/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/cameroun/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.CAMEROON_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Cameroun',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  CAMEROON_INFLUENCER_MALE_01: {
    voiceProfileId: 'CAMEROON_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Cameroun',
    language: 'French',
    gender: 'male',
    persona: 'Paul',
    masterVoiceSample: 'services/voice-profiles/cameroun/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/cameroun/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.CAMEROON_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Cameroun',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇨🇬 CONGO
  CONGO_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'CONGO_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Congo',
    language: 'French',
    gender: 'female',
    persona: 'Grâce',
    masterVoiceSample: 'services/voice-profiles/congo/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/congo/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.CONGO_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Congo',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  CONGO_INFLUENCER_MALE_01: {
    voiceProfileId: 'CONGO_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Congo',
    language: 'French',
    gender: 'male',
    persona: 'Dieudonné',
    masterVoiceSample: 'services/voice-profiles/congo/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/congo/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.CONGO_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Congo',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇬🇭 GHANA
  GHANA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'GHANA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Ghana',
    language: 'English',
    gender: 'female',
    persona: 'Abena',
    masterVoiceSample: 'services/voice-profiles/ghana/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/ghana/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.GHANA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Ghana',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  GHANA_INFLUENCER_MALE_01: {
    voiceProfileId: 'GHANA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Ghana',
    language: 'English',
    gender: 'male',
    persona: 'Kofi',
    masterVoiceSample: 'services/voice-profiles/ghana/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/ghana/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.GHANA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Ghana',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇲🇦 MAROC
  MOROCCO_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'MOROCCO_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Maroc',
    language: 'French',
    gender: 'female',
    persona: 'Salma',
    masterVoiceSample: 'services/voice-profiles/maroc/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/maroc/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.MOROCCO_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Maroc',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  MOROCCO_INFLUENCER_MALE_01: {
    voiceProfileId: 'MOROCCO_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Maroc',
    language: 'French',
    gender: 'male',
    persona: 'Youssef',
    masterVoiceSample: 'services/voice-profiles/maroc/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/maroc/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.MOROCCO_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Maroc',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇿🇦 AFRIQUE DU SUD
  SOUTH_AFRICA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'SOUTH_AFRICA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Afrique du Sud',
    language: 'English',
    gender: 'female',
    persona: 'Lerato',
    masterVoiceSample: 'services/voice-profiles/afrique-du-sud/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/afrique-du-sud/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.SOUTH_AFRICA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Afrique du Sud',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  SOUTH_AFRICA_INFLUENCER_MALE_01: {
    voiceProfileId: 'SOUTH_AFRICA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Afrique du Sud',
    language: 'English',
    gender: 'male',
    persona: 'Sipho',
    masterVoiceSample: 'services/voice-profiles/afrique-du-sud/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/afrique-du-sud/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.SOUTH_AFRICA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Afrique du Sud',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇰🇪 KENYA
  KENYA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'KENYA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Kenya',
    language: 'English',
    gender: 'female',
    persona: 'Zuri',
    masterVoiceSample: 'services/voice-profiles/kenya/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/kenya/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.KENYA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Kenya',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  KENYA_INFLUENCER_MALE_01: {
    voiceProfileId: 'KENYA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Kenya',
    language: 'English',
    gender: 'male',
    persona: 'Juma',
    masterVoiceSample: 'services/voice-profiles/kenya/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/kenya/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.KENYA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Kenya',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇬🇦 GABON
  GABON_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'GABON_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Gabon',
    language: 'French',
    gender: 'female',
    persona: 'Brenda',
    masterVoiceSample: 'services/voice-profiles/gabon/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/gabon/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.GABON_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Gabon',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  GABON_INFLUENCER_MALE_01: {
    voiceProfileId: 'GABON_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Gabon',
    language: 'French',
    gender: 'male',
    persona: 'Landry',
    masterVoiceSample: 'services/voice-profiles/gabon/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/gabon/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.GABON_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Gabon',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇧🇯 BÉNIN
  BENIN_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'BENIN_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Bénin',
    language: 'French',
    gender: 'female',
    persona: 'Sênami',
    masterVoiceSample: 'services/voice-profiles/benin/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/benin/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.BENIN_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Bénin',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  BENIN_INFLUENCER_MALE_01: {
    voiceProfileId: 'BENIN_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Bénin',
    language: 'French',
    gender: 'male',
    persona: 'Gildas',
    masterVoiceSample: 'services/voice-profiles/benin/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/benin/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.BENIN_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Bénin',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇧🇫 BURKINA FASO
  BURKINA_FASO_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'BURKINA_FASO_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Burkina Faso',
    language: 'French',
    gender: 'female',
    persona: 'Assetou',
    masterVoiceSample: 'services/voice-profiles/burkina-faso/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/burkina-faso/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.BURKINA_FASO_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Burkina Faso',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  BURKINA_FASO_INFLUENCER_MALE_01: {
    voiceProfileId: 'BURKINA_FASO_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Burkina Faso',
    language: 'French',
    gender: 'male',
    persona: 'Wendkouni',
    masterVoiceSample: 'services/voice-profiles/burkina-faso/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/burkina-faso/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.BURKINA_FASO_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Burkina Faso',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇲🇱 MALI
  MALI_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'MALI_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Mali',
    language: 'French',
    gender: 'female',
    persona: 'Oumou',
    masterVoiceSample: 'services/voice-profiles/mali/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/mali/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.MALI_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Mali',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  MALI_INFLUENCER_MALE_01: {
    voiceProfileId: 'MALI_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Mali',
    language: 'French',
    gender: 'male',
    persona: 'Modibo',
    masterVoiceSample: 'services/voice-profiles/mali/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/mali/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.MALI_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Mali',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇹🇬 TOGO
  TOGO_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'TOGO_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Togo',
    language: 'French',
    gender: 'female',
    persona: 'Akossiwa',
    masterVoiceSample: 'services/voice-profiles/togo/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/togo/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TOGO_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Togo',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  TOGO_INFLUENCER_MALE_01: {
    voiceProfileId: 'TOGO_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Togo',
    language: 'French',
    gender: 'male',
    persona: 'Koffi',
    masterVoiceSample: 'services/voice-profiles/togo/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/togo/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TOGO_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Togo',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇹🇳 TUNISIE
  TUNISIA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'TUNISIA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Tunisie',
    language: 'French',
    gender: 'female',
    persona: 'Amira',
    masterVoiceSample: 'services/voice-profiles/tunisie/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/tunisie/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TUNISIA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Tunisie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  TUNISIA_INFLUENCER_MALE_01: {
    voiceProfileId: 'TUNISIA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Tunisie',
    language: 'French',
    gender: 'male',
    persona: 'Yassine',
    masterVoiceSample: 'services/voice-profiles/tunisie/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/tunisie/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TUNISIA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Tunisie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇩🇿 ALGÉRIE
  ALGERIA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'ALGERIA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Algérie',
    language: 'French',
    gender: 'female',
    persona: 'Yasmine',
    masterVoiceSample: 'services/voice-profiles/algerie/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/algerie/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.ALGERIA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Algérie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  ALGERIA_INFLUENCER_MALE_01: {
    voiceProfileId: 'ALGERIA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Algérie',
    language: 'French',
    gender: 'male',
    persona: 'Karim',
    masterVoiceSample: 'services/voice-profiles/algerie/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/algerie/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.ALGERIA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Algérie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇪🇬 ÉGYPTE
  EGYPT_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'EGYPT_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Égypte',
    language: 'English',
    gender: 'female',
    persona: 'Layla',
    masterVoiceSample: 'services/voice-profiles/egypte/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/egypte/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.EGYPT_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Égypte',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  EGYPT_INFLUENCER_MALE_01: {
    voiceProfileId: 'EGYPT_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Égypte',
    language: 'English',
    gender: 'male',
    persona: 'Tarek',
    masterVoiceSample: 'services/voice-profiles/egypte/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/egypte/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.EGYPT_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Égypte',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇺🇬 OUGANDA
  UGANDA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'UGANDA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Ouganda',
    language: 'English',
    gender: 'female',
    persona: 'Namatai',
    masterVoiceSample: 'services/voice-profiles/ouganda/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/ouganda/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.UGANDA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Ouganda',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  UGANDA_INFLUENCER_MALE_01: {
    voiceProfileId: 'UGANDA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Ouganda',
    language: 'English',
    gender: 'male',
    persona: 'Ivan',
    masterVoiceSample: 'services/voice-profiles/ouganda/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/ouganda/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.UGANDA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Ouganda',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },

  // 🇹🇿 TANZANIE
  TANZANIA_INFLUENCER_FEMALE_01: {
    voiceProfileId: 'TANZANIA_INFLUENCER_FEMALE_01',
    version: '1.0.0',
    country: 'Tanzanie',
    language: 'English',
    gender: 'female',
    persona: 'Neema',
    masterVoiceSample: 'services/voice-profiles/tanzanie/influencer/female-01/master.wav',
    consentAudio: 'services/voice-profiles/tanzanie/influencer/female-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TANZANIA_INFLUENCER_FEMALE_01_KEY || '',
    accentProfile: 'Tanzanie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
  TANZANIA_INFLUENCER_MALE_01: {
    voiceProfileId: 'TANZANIA_INFLUENCER_MALE_01',
    version: '1.0.0',
    country: 'Tanzanie',
    language: 'English',
    gender: 'male',
    persona: 'Baraka',
    masterVoiceSample: 'services/voice-profiles/tanzanie/influencer/male-01/master.wav',
    consentAudio: 'services/voice-profiles/tanzanie/influencer/male-01/consent.wav',
    consentStatus: 'APPROVED',
    voiceCloningKey: process.env.TANZANIA_INFLUENCER_MALE_01_KEY || '',
    accentProfile: 'Tanzanie',
    styleProfile: 'Influencer',
    basePace: 1.0,
    provider: 'google',
    providerModel: 'chirp-3',
  },
};

/**
 * Returns a voice profile matching a country ID (e.g. 'SN', 'CI', 'NG') and optional gender ('male' | 'female').
 * Falls back to the female profile of the country, then Senegal if unmatched.
 */
export function getVoiceProfileByCountryAndGender(countryId: string, gender: 'male' | 'female' = 'female'): VoiceProfile {
  const normalizedCountry = (countryId || 'SN').toUpperCase();
  
  const countryMapping: Record<string, string> = {
    NG: 'NIGERIA',
    CI: 'COTE_D_IVOIRE',
    CM: 'CAMEROON',
    SN: 'SENEGAL',
    CG: 'CONGO',
    CD: 'CONGO',
    GH: 'GHANA',
    MA: 'MOROCCO',
    ZA: 'SOUTH_AFRICA',
    KE: 'KENYA',
    GA: 'GABON',
    BJ: 'BENIN',
    BF: 'BURKINA_FASO',
    ML: 'MALI',
    TG: 'TOGO',
    TN: 'TUNISIA',
    DZ: 'ALGERIA',
    EG: 'EGYPT',
    UG: 'UGANDA',
    TZ: 'TANZANIA',
    RW: 'RWANDA',
  };

  const prefix = countryMapping[normalizedCountry] || 'SENEGAL';
  const targetGender = gender.toUpperCase();
  const targetKey = `${prefix}_INFLUENCER_${targetGender}_01`;

  if (VOICE_PROFILES[targetKey]) {
    return VOICE_PROFILES[targetKey];
  }

  // Fallback to female profile for the country
  const fallbackFemaleKey = `${prefix}_INFLUENCER_FEMALE_01`;
  if (VOICE_PROFILES[fallbackFemaleKey]) {
    return VOICE_PROFILES[fallbackFemaleKey];
  }

  // Ultimate fallback
  return VOICE_PROFILES.SENEGAL_INFLUENCER_FEMALE_01;
}
