import { VoiceIdentity, VoiceTier, VocalPersonality, ContentStyle } from '../types';

export const STARTER_COUNTRIES = ['NG', 'CI', 'CM', 'SN', 'CG'];
export const CREATOR_COUNTRIES = ['NG', 'CI', 'CM', 'SN', 'CG', 'GH', 'MA', 'ZA', 'KE', 'GA'];
export const PRO_COUNTRIES = [
  'NG', 'CI', 'CM', 'SN', 'CG', 'GH', 'MA', 'ZA', 'KE', 'GA',
  'BJ', 'BF', 'ML', 'TG', 'TN', 'DZ', 'EG', 'UG', 'TZ', 'RW'
];

export const VOICE_REGISTRY: Record<string, VoiceIdentity> = {
  // NG - Nigeria
  'NG_BLESSING_01': {
    voiceId: 'NG_BLESSING_01',
    persona: 'Blessing',
    countryId: 'NG',
    countryName: "Nigeria",
    flag: '🇳🇬',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix chaleureuse et naturelle de Abuja",
    description_en: "Warm, natural voice from Abuja",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'commercial',
    defaultEmotion: 'neutral',
    requiredPlan: 'pro',
  },
  'NG_NGOZI_02': {
    voiceId: 'NG_NGOZI_02',
    persona: 'Ngozi',
    countryId: 'NG',
    countryName: "Nigeria",
    flag: '🇳🇬',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix énergique et percutante de Abuja",
    description_en: "Energetic, punchy voice from Abuja",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'creator',
  },
  'NG_EMEKA_03': {
    voiceId: 'NG_EMEKA_03',
    persona: 'Emeka',
    countryId: 'NG',
    countryName: "Nigeria",
    flag: '🇳🇬',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Abuja",
    description_en: "Deep, authoritative voice from Abuja",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // CI - Côte d'Ivoire
  'CI_AMINATA_01': {
    voiceId: 'CI_AMINATA_01',
    persona: 'Aminata',
    countryId: 'CI',
    countryName: "Côte d'Ivoire",
    flag: '🇨🇮',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Yamoussoukro",
    description_en: "Warm, natural voice from Yamoussoukro",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'CI_MARIAM_02': {
    voiceId: 'CI_MARIAM_02',
    persona: 'Mariam',
    countryId: 'CI',
    countryName: "Côte d'Ivoire",
    flag: '🇨🇮',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Yamoussoukro",
    description_en: "Energetic, punchy voice from Yamoussoukro",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'CI_KOUASSI_03': {
    voiceId: 'CI_KOUASSI_03',
    persona: 'Kouassi',
    countryId: 'CI',
    countryName: "Côte d'Ivoire",
    flag: '🇨🇮',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Yamoussoukro",
    description_en: "Deep, authoritative voice from Yamoussoukro",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // CM - Cameroun
  'CM_CHANTAL_01': {
    voiceId: 'CM_CHANTAL_01',
    persona: 'Chantal',
    countryId: 'CM',
    countryName: "Cameroun",
    flag: '🇨🇲',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Yaoundé",
    description_en: "Warm, natural voice from Yaoundé",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'CM_MARIE_02': {
    voiceId: 'CM_MARIE_02',
    persona: 'Marie',
    countryId: 'CM',
    countryName: "Cameroun",
    flag: '🇨🇲',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Yaoundé",
    description_en: "Energetic, punchy voice from Yaoundé",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'CM_PAUL_03': {
    voiceId: 'CM_PAUL_03',
    persona: 'Paul',
    countryId: 'CM',
    countryName: "Cameroun",
    flag: '🇨🇲',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Yaoundé",
    description_en: "Deep, authoritative voice from Yaoundé",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // SN - Sénégal
  'SN_FATOU_01': {
    voiceId: 'SN_FATOU_01',
    persona: 'Fatou',
    countryId: 'SN',
    countryName: "Sénégal",
    flag: '🇸🇳',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Dakar",
    description_en: "Warm, natural voice from Dakar",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'SN_AWA_02': {
    voiceId: 'SN_AWA_02',
    persona: 'Awa',
    countryId: 'SN',
    countryName: "Sénégal",
    flag: '🇸🇳',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Dakar",
    description_en: "Energetic, punchy voice from Dakar",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'SN_BABACAR_03': {
    voiceId: 'SN_BABACAR_03',
    persona: 'Babacar',
    countryId: 'SN',
    countryName: "Sénégal",
    flag: '🇸🇳',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Dakar",
    description_en: "Deep, authoritative voice from Dakar",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // CG - Congo
  'CG_GRACE_01': {
    voiceId: 'CG_GRACE_01',
    persona: 'Grâce',
    countryId: 'CG',
    countryName: "Congo",
    flag: '🇨🇬',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Brazzaville",
    description_en: "Warm, natural voice from Brazzaville",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'CG_BEATRICE_02': {
    voiceId: 'CG_BEATRICE_02',
    persona: 'Béatrice',
    countryId: 'CG',
    countryName: "Congo",
    flag: '🇨🇬',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Brazzaville",
    description_en: "Energetic, punchy voice from Brazzaville",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'CG_FISTON_03': {
    voiceId: 'CG_FISTON_03',
    persona: 'Fiston',
    countryId: 'CG',
    countryName: "Congo",
    flag: '🇨🇬',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Brazzaville",
    description_en: "Deep, authoritative voice from Brazzaville",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // GH - Ghana
  'GH_AKUA_01': {
    voiceId: 'GH_AKUA_01',
    persona: 'Akua',
    countryId: 'GH',
    countryName: "Ghana",
    flag: '🇬🇭',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Accra",
    description_en: "Warm, natural voice from Accra",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'GH_ABENA_02': {
    voiceId: 'GH_ABENA_02',
    persona: 'Abena',
    countryId: 'GH',
    countryName: "Ghana",
    flag: '🇬🇭',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Accra",
    description_en: "Energetic, punchy voice from Accra",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'GH_KWAME_03': {
    voiceId: 'GH_KWAME_03',
    persona: 'Kwame',
    countryId: 'GH',
    countryName: "Ghana",
    flag: '🇬🇭',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Accra",
    description_en: "Deep, authoritative voice from Accra",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // MA - Maroc
  'MA_LEILA_01': {
    voiceId: 'MA_LEILA_01',
    persona: 'Leïla',
    countryId: 'MA',
    countryName: "Maroc",
    flag: '🇲🇦',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Rabat",
    description_en: "Warm, natural voice from Rabat",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'MA_YASMINE_02': {
    voiceId: 'MA_YASMINE_02',
    persona: 'Yasmine',
    countryId: 'MA',
    countryName: "Maroc",
    flag: '🇲🇦',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Rabat",
    description_en: "Energetic, punchy voice from Rabat",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'MA_YOUSSEF_03': {
    voiceId: 'MA_YOUSSEF_03',
    persona: 'Youssef',
    countryId: 'MA',
    countryName: "Maroc",
    flag: '🇲🇦',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Rabat",
    description_en: "Deep, authoritative voice from Rabat",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // ZA - Afrique du Sud
  'ZA_NALEDI_01': {
    voiceId: 'ZA_NALEDI_01',
    persona: 'Naledi',
    countryId: 'ZA',
    countryName: "Afrique du Sud",
    flag: '🇿🇦',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Pretoria",
    description_en: "Warm, natural voice from Pretoria",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'ZA_THANDI_02': {
    voiceId: 'ZA_THANDI_02',
    persona: 'Thandi',
    countryId: 'ZA',
    countryName: "Afrique du Sud",
    flag: '🇿🇦',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Pretoria",
    description_en: "Energetic, punchy voice from Pretoria",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'ZA_SIPHO_03': {
    voiceId: 'ZA_SIPHO_03',
    persona: 'Sipho',
    countryId: 'ZA',
    countryName: "Afrique du Sud",
    flag: '🇿🇦',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Pretoria",
    description_en: "Deep, authoritative voice from Pretoria",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // KE - Kenya
  'KE_WANJIRU_01': {
    voiceId: 'KE_WANJIRU_01',
    persona: 'Wanjiru',
    countryId: 'KE',
    countryName: "Kenya",
    flag: '🇰🇪',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Nairobi",
    description_en: "Warm, natural voice from Nairobi",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'KE_AISHA_02': {
    voiceId: 'KE_AISHA_02',
    persona: 'Aisha',
    countryId: 'KE',
    countryName: "Kenya",
    flag: '🇰🇪',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Nairobi",
    description_en: "Energetic, punchy voice from Nairobi",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'KE_KAMAU_03': {
    voiceId: 'KE_KAMAU_03',
    persona: 'Kamau',
    countryId: 'KE',
    countryName: "Kenya",
    flag: '🇰🇪',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Nairobi",
    description_en: "Deep, authoritative voice from Nairobi",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // GA - Gabon
  'GA_SYLVIE_01': {
    voiceId: 'GA_SYLVIE_01',
    persona: 'Sylvie',
    countryId: 'GA',
    countryName: "Gabon",
    flag: '🇬🇦',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Libreville",
    description_en: "Warm, natural voice from Libreville",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'GA_ORNELLA_02': {
    voiceId: 'GA_ORNELLA_02',
    persona: 'Ornella',
    countryId: 'GA',
    countryName: "Gabon",
    flag: '🇬🇦',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Libreville",
    description_en: "Energetic, punchy voice from Libreville",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'GA_HERVE_03': {
    voiceId: 'GA_HERVE_03',
    persona: 'Hervé',
    countryId: 'GA',
    countryName: "Gabon",
    flag: '🇬🇦',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Libreville",
    description_en: "Deep, authoritative voice from Libreville",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // BJ - Bénin
  'BJ_ADJO_01': {
    voiceId: 'BJ_ADJO_01',
    persona: 'Adjo',
    countryId: 'BJ',
    countryName: "Bénin",
    flag: '🇧🇯',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Porto-Novo",
    description_en: "Warm, natural voice from Porto-Novo",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'BJ_FIFAME_02': {
    voiceId: 'BJ_FIFAME_02',
    persona: 'Fifame',
    countryId: 'BJ',
    countryName: "Bénin",
    flag: '🇧🇯',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Porto-Novo",
    description_en: "Energetic, punchy voice from Porto-Novo",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'BJ_KOFFI_03': {
    voiceId: 'BJ_KOFFI_03',
    persona: 'Koffi',
    countryId: 'BJ',
    countryName: "Bénin",
    flag: '🇧🇯',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Porto-Novo",
    description_en: "Deep, authoritative voice from Porto-Novo",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // BF - Burkina Faso
  'BF_RASMATA_01': {
    voiceId: 'BF_RASMATA_01',
    persona: 'Rasmata',
    countryId: 'BF',
    countryName: "Burkina Faso",
    flag: '🇧🇫',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Ouagadougou",
    description_en: "Warm, natural voice from Ouagadougou",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'BF_MARIAM_02': {
    voiceId: 'BF_MARIAM_02',
    persona: 'Mariam',
    countryId: 'BF',
    countryName: "Burkina Faso",
    flag: '🇧🇫',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Ouagadougou",
    description_en: "Energetic, punchy voice from Ouagadougou",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'BF_IBRAHIM_03': {
    voiceId: 'BF_IBRAHIM_03',
    persona: 'Ibrahim',
    countryId: 'BF',
    countryName: "Burkina Faso",
    flag: '🇧🇫',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Ouagadougou",
    description_en: "Deep, authoritative voice from Ouagadougou",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // ML - Mali
  'ML_FATOUMATA_01': {
    voiceId: 'ML_FATOUMATA_01',
    persona: 'Fatoumata',
    countryId: 'ML',
    countryName: "Mali",
    flag: '🇲🇱',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Bamako",
    description_en: "Warm, natural voice from Bamako",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'ML_OUMOU_02': {
    voiceId: 'ML_OUMOU_02',
    persona: 'Oumou',
    countryId: 'ML',
    countryName: "Mali",
    flag: '🇲🇱',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Bamako",
    description_en: "Energetic, punchy voice from Bamako",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'ML_MOUSSA_03': {
    voiceId: 'ML_MOUSSA_03',
    persona: 'Moussa',
    countryId: 'ML',
    countryName: "Mali",
    flag: '🇲🇱',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Bamako",
    description_en: "Deep, authoritative voice from Bamako",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // TG - Togo
  'TG_AMA_01': {
    voiceId: 'TG_AMA_01',
    persona: 'Ama',
    countryId: 'TG',
    countryName: "Togo",
    flag: '🇹🇬',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Lomé",
    description_en: "Warm, natural voice from Lomé",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'TG_AKOSSIWA_02': {
    voiceId: 'TG_AKOSSIWA_02',
    persona: 'Akossiwa',
    countryId: 'TG',
    countryName: "Togo",
    flag: '🇹🇬',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Lomé",
    description_en: "Energetic, punchy voice from Lomé",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'TG_KODJO_03': {
    voiceId: 'TG_KODJO_03',
    persona: 'Kodjo',
    countryId: 'TG',
    countryName: "Togo",
    flag: '🇹🇬',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Lomé",
    description_en: "Deep, authoritative voice from Lomé",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // TN - Tunisie
  'TN_AMIRA_01': {
    voiceId: 'TN_AMIRA_01',
    persona: 'Amira',
    countryId: 'TN',
    countryName: "Tunisie",
    flag: '🇹🇳',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Tunis",
    description_en: "Warm, natural voice from Tunis",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'TN_SELMA_02': {
    voiceId: 'TN_SELMA_02',
    persona: 'Selma',
    countryId: 'TN',
    countryName: "Tunisie",
    flag: '🇹🇳',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Tunis",
    description_en: "Energetic, punchy voice from Tunis",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'TN_MEHDI_03': {
    voiceId: 'TN_MEHDI_03',
    persona: 'Mehdi',
    countryId: 'TN',
    countryName: "Tunisie",
    flag: '🇹🇳',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Tunis",
    description_en: "Deep, authoritative voice from Tunis",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // DZ - Algérie
  'DZ_DJAMILA_01': {
    voiceId: 'DZ_DJAMILA_01',
    persona: 'Djamila',
    countryId: 'DZ',
    countryName: "Algérie",
    flag: '🇩🇿',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Alger",
    description_en: "Warm, natural voice from Alger",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'DZ_NADIA_02': {
    voiceId: 'DZ_NADIA_02',
    persona: 'Nadia',
    countryId: 'DZ',
    countryName: "Algérie",
    flag: '🇩🇿',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Alger",
    description_en: "Energetic, punchy voice from Alger",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'DZ_KARIM_03': {
    voiceId: 'DZ_KARIM_03',
    persona: 'Karim',
    countryId: 'DZ',
    countryName: "Algérie",
    flag: '🇩🇿',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Alger",
    description_en: "Deep, authoritative voice from Alger",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // EG - Égypte
  'EG_NOUR_01': {
    voiceId: 'EG_NOUR_01',
    persona: 'Nour',
    countryId: 'EG',
    countryName: "Égypte",
    flag: '🇪🇬',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Le Caire",
    description_en: "Warm, natural voice from Le Caire",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'EG_YASMIN_02': {
    voiceId: 'EG_YASMIN_02',
    persona: 'Yasmin',
    countryId: 'EG',
    countryName: "Égypte",
    flag: '🇪🇬',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Le Caire",
    description_en: "Energetic, punchy voice from Le Caire",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'EG_OMAR_03': {
    voiceId: 'EG_OMAR_03',
    persona: 'Omar',
    countryId: 'EG',
    countryName: "Égypte",
    flag: '🇪🇬',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Le Caire",
    description_en: "Deep, authoritative voice from Le Caire",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // UG - Ouganda
  'UG_NAMUKASA_01': {
    voiceId: 'UG_NAMUKASA_01',
    persona: 'Namukasa',
    countryId: 'UG',
    countryName: "Ouganda",
    flag: '🇺🇬',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Kampala",
    description_en: "Warm, natural voice from Kampala",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'UG_AKELLO_02': {
    voiceId: 'UG_AKELLO_02',
    persona: 'Akello',
    countryId: 'UG',
    countryName: "Ouganda",
    flag: '🇺🇬',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Kampala",
    description_en: "Energetic, punchy voice from Kampala",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'UG_OKELLO_03': {
    voiceId: 'UG_OKELLO_03',
    persona: 'Okello',
    countryId: 'UG',
    countryName: "Ouganda",
    flag: '🇺🇬',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Kampala",
    description_en: "Deep, authoritative voice from Kampala",
    providerVoiceId: 'Fenrir',
    voiceVariant: 'voice1',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

  // TZ - Tanzanie
  'TZ_REHEMA_01': {
    voiceId: 'TZ_REHEMA_01',
    persona: 'Rehema',
    countryId: 'TZ',
    countryName: "Tanzanie",
    flag: '🇹🇿',
    gender: 'female',
    tier: 'dynamic',
    description_fr: "Voix chaleureuse et naturelle de Dodoma",
    description_en: "Warm, natural voice from Dodoma",
    providerVoiceId: 'Aoede',
    voiceVariant: 'voice1',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'neutral',
    requiredPlan: 'creator',
  },
  'TZ_ZAWADI_02': {
    voiceId: 'TZ_ZAWADI_02',
    persona: 'Zawadi',
    countryId: 'TZ',
    countryName: "Tanzanie",
    flag: '🇹🇿',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Dodoma",
    description_en: "Energetic, punchy voice from Dodoma",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'TZ_BARAKA_03': {
    voiceId: 'TZ_BARAKA_03',
    persona: 'Baraka',
    countryId: 'TZ',
    countryName: "Tanzanie",
    flag: '🇹🇿',
    gender: 'male',
    tier: 'natural',
    description_fr: "Voix grave et autoritaire de Dodoma",
    description_en: "Deep, authoritative voice from Dodoma",
    providerVoiceId: 'Puck',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'serious',
    requiredPlan: 'free',
  },

  // RW - Rwanda
  'RW_UWASE_01': {
    voiceId: 'RW_UWASE_01',
    persona: 'Uwase',
    countryId: 'RW',
    countryName: "Rwanda",
    flag: '🇷🇼',
    gender: 'female',
    tier: 'natural',
    description_fr: "Voix chaleureuse et naturelle de Kigali",
    description_en: "Warm, natural voice from Kigali",
    providerVoiceId: 'Kore',
    voiceVariant: 'voice1',
    defaultPersonality: 'narrator',
    defaultContentStyle: 'narration',
    defaultEmotion: 'neutral',
    requiredPlan: 'free',
  },
  'RW_MUTONI_02': {
    voiceId: 'RW_MUTONI_02',
    persona: 'Mutoni',
    countryId: 'RW',
    countryName: "Rwanda",
    flag: '🇷🇼',
    gender: 'female',
    tier: 'premium',
    description_fr: "Voix énergique et percutante de Kigali",
    description_en: "Energetic, punchy voice from Kigali",
    providerVoiceId: 'Leda',
    voiceVariant: 'voice2',
    defaultPersonality: 'influencer',
    defaultContentStyle: 'tiktok',
    defaultEmotion: 'energetic',
    requiredPlan: 'pro',
  },
  'RW_HABIMANA_03': {
    voiceId: 'RW_HABIMANA_03',
    persona: 'Habimana',
    countryId: 'RW',
    countryName: "Rwanda",
    flag: '🇷🇼',
    gender: 'male',
    tier: 'dynamic',
    description_fr: "Voix grave et autoritaire de Kigali",
    description_en: "Deep, authoritative voice from Kigali",
    providerVoiceId: 'Charon',
    voiceVariant: 'voice2',
    defaultPersonality: 'radio_host',
    defaultContentStyle: 'youtube',
    defaultEmotion: 'serious',
    requiredPlan: 'creator',
  },

};

/** Get all voices for a specific country */
export function getVoicesForCountry(countryId: string): VoiceIdentity[] {
  return Object.values(VOICE_REGISTRY).filter((v) => v.countryId === countryId);
}

/** Get a voice by its unique ID */
export function getVoiceById(voiceId: string): VoiceIdentity | undefined {
  return VOICE_REGISTRY[voiceId];
}

/** Get all 60 voices */
export function getAllVoices(): VoiceIdentity[] {
  return Object.values(VOICE_REGISTRY);
}

/** Get voices accessible for a given plan */
export function getAccessibleVoices(planId: 'free' | 'creator' | 'pro'): VoiceIdentity[] {
  const accessibleCountries = getAccessibleCountryIds(planId);
  return getAllVoices().filter((v) => {
    if (!accessibleCountries.includes(v.countryId)) return false;
    if (planId === 'free') return v.tier === 'natural';
    if (planId === 'creator') return v.tier === 'natural' || v.tier === 'dynamic';
    return true; // pro gets all
  });
}

/** Get accessible countries for a plan */
export function getAccessibleCountryIds(planId: 'free' | 'creator' | 'pro'): string[] {
  if (planId === 'free') return STARTER_COUNTRIES;
  if (planId === 'creator') return CREATOR_COUNTRIES;
  return PRO_COUNTRIES;
}

/** Migrate an old history item to the closest voice_id */
export function migrateToVoiceId(countryId: string, gender: 'male' | 'female'): string | null {
  const voicesForCountry = getVoicesForCountry(countryId);
  if (voicesForCountry.length === 0) return null;
  
  const match = voicesForCountry.find(v => v.gender === gender);
  return match ? match.voiceId : null;
}
