import { VoiceDNA } from '../types';

export const VOICE_DNA: Record<string, VoiceDNA> = {
  'NG': {
    countryId: 'NG',
    region: 'West Africa',
    capital: 'Abuja/Lagos',
    localLanguages: ['Hausa', 'Yoruba', 'Igbo', 'Pidgin English'],
    speechMelody: 'Highly melodic and dynamic Nigerian intonation. Pitch rises vibrantly on key nouns and action verbs, carrying a commanding yet warm cadence.',
    consonantStyle: 'Crisp, firm, and percussive consonants. Hard "t" and "d" sounds with deep pectoral resonance; clear bilabial articulation without weak reduction.',
    rhythmPattern: 'Syllable-timed, punchy staccato rhythm with rapid, confident delivery and natural emphasis on action phrases.',
    culturalContext: 'Extremely confident, charismatic, direct, and persuasive. Inspired by Lagos urban energy and rich oral traditions.',
    antiPatterns: ['British RP English', 'Standard American English', 'Australian English', 'South African English', 'Monotone robotic TTS'],
    defaultWarmth: 8,
    defaultConfidence: 9,
    defaultEnergy: 9
  },
  'CI': {
    countryId: 'CI',
    region: 'West Africa',
    capital: 'Abidjan',
    localLanguages: ['Baoulé', 'Dioula', 'Bété', 'Nouchi'],
    speechMelody: 'Warm, musical, and expressive Ivorian lilt. Phrases naturally end with a gentle rising intonation that invites warmth and connection.',
    consonantStyle: 'Softened tapped "r" sounds, rich open nasal vowels (an, on, in), clear bilabials, and smooth consonant transitions.',
    rhythmPattern: 'Bouncy, syncopated, and rhythmic. Key vowels are slightly elongated for emphasis, reflecting Nouchi speech cadence.',
    culturalContext: 'Joyful, hospitable, convivial, and deeply expressive. Captures the vibrant, welcoming spirit of Abidjan.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Standard European French', 'Monotone delivery'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'CM': {
    countryId: 'CM',
    region: 'Central Africa',
    capital: 'Yaoundé/Douala',
    localLanguages: ['Ewondo', 'Duala', 'Fulfulde', 'Camfranglais'],
    speechMelody: 'Deep, authoritative, and grounded pitch. Heavy chest resonance with deliberate downward intonations at sentence endings.',
    consonantStyle: 'Strong, percussive consonants. Distinct, un-softened plosives (p, b, t, d, k, g) articulated with clear firmness.',
    rhythmPattern: 'Measured, steady, and deliberate pacing with powerful, even stress across words conveying gravitas.',
    culturalContext: 'Assertive, serious, respectful, and dignified. Represents Cameroonian pride, authority, and calm strength.',
    antiPatterns: ['Parisian French', 'European French', 'Senegalese French', 'High-pitched rushed speech'],
    defaultWarmth: 6,
    defaultConfidence: 9,
    defaultEnergy: 7
  },
  'SN': {
    countryId: 'SN',
    region: 'West Africa',
    capital: 'Dakar',
    localLanguages: ['Wolof', 'Pulaar', 'Jola'],
    speechMelody: 'Smooth, poetic, and fluid intonation. Features gentle cascading pitch transitions with polite, dignified vocal contours.',
    consonantStyle: 'Soft, clean consonants with distinct Wolof-influenced open vowels and lightly tapped palatal sounds.',
    rhythmPattern: 'Continuous, elegant, and lyrical flow. Sentences glide effortlessly with harmonious breathing pauses.',
    culturalContext: 'Infused with "Teranga" (world-famous Senegalese hospitality). Respectful, serene, noble, and deeply welcoming.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Harsh staccato', 'Aggressive delivery'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'CD': {
    countryId: 'CD',
    region: 'Central Africa',
    capital: 'Kinshasa',
    localLanguages: ['Lingala', 'Swahili', 'Tshiluba', 'Kikongo'],
    speechMelody: 'Vibrant, melodious, and highly expressive. Pitch moves in graceful tonal arches shaped by Lingala musicality.',
    consonantStyle: 'Soft, rounded consonants with open, bright, sustained vowels and smooth vocalic resonance.',
    rhythmPattern: 'Lively, dance-like, syncopated cadence with rhythmic pauses and expressive vocal warmth.',
    culturalContext: 'Flamboyant, artistic, warm, and captivating. Reflects Kinshasa\'s legendary music and cultural energy.',
    antiPatterns: ['Parisian French', 'Belgian French', 'Flat monotone delivery', 'Dull robotic speech'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  'GH': {
    countryId: 'GH',
    region: 'West Africa',
    capital: 'Accra',
    localLanguages: ['Twi', 'Ga', 'Ewe', 'Fante'],
    speechMelody: 'Polite, melodic, and dignified pitch contour with gentle rising inflections drawn from Twi tonal patterns.',
    consonantStyle: 'Crisp, clean, articulate consonants with full, rounded vowels and precise enunciation.',
    rhythmPattern: 'Measured, steady, and clear. Balanced syllable-timing designed for maximum clarity and respect.',
    culturalContext: 'Warm, courteous, educated, and hospitable. Reflects Ghanaian royal dignity and respectful storytelling.',
    antiPatterns: ['Standard American English', 'British RP English', 'Harsh aggressive delivery'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  'MA': {
    countryId: 'MA',
    region: 'North Africa',
    capital: 'Casablanca/Rabat',
    localLanguages: ['Darija', 'Tamazight'],
    speechMelody: 'Fast, intricate, undulating melody blending Moroccan Arabic vocal contours with precise French phrasing.',
    consonantStyle: 'Rich guttural and pharyngeal resonance (kh, q, h) combined with crisp, forward bilabial articulation.',
    rhythmPattern: 'Dynamic contrast between swift staccato word bursts and smooth, elegant sentence transitions.',
    culturalContext: 'Sophisticated, warm, sharp, and cosmopolitan. Reflects North African Maghrebi heritage and Mediterranean flair.',
    antiPatterns: ['Parisian French', 'Levantine Arabic', 'Gulf Arabic', 'Flat European delivery'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'ZA': {
    countryId: 'ZA',
    region: 'Southern Africa',
    capital: 'Johannesburg',
    localLanguages: ['Zulu', 'Xhosa', 'Afrikaans', 'Sotho'],
    speechMelody: 'Broad, resonant, open vocal melody. Rich back-of-throat resonance with dynamic pitch variations.',
    consonantStyle: 'Crisp, sharp articulation of "t" and "k", subtle glottal stops, and firm consonant releases.',
    rhythmPattern: 'Punchy, energetic, and rhythmic with smooth transitions between deliberate emphasis and rapid bursts.',
    culturalContext: 'Bold, modern, confident, and direct. Grounded in Ubuntu spirit and Johannesburg urban vibrancy.',
    antiPatterns: ['British RP English', 'Australian English', 'Standard American English', 'Robotic TTS'],
    defaultWarmth: 7,
    defaultConfidence: 9,
    defaultEnergy: 8
  },
  'KE': {
    countryId: 'KE',
    region: 'East Africa',
    capital: 'Nairobi',
    localLanguages: ['Swahili', 'Kikuyu', 'Luo', 'Sheng'],
    speechMelody: 'Bright, rhythmic, and upbeat intonation. Emphasis on penultimate syllables following Swahili speech rules.',
    consonantStyle: 'Clear, strong consonants with rolled or tapped "r" and pure, un-diphthongized open vowels.',
    rhythmPattern: 'Steady, punchy, syllable-timed staccato rhythm with crisp, energetic transitions.',
    culturalContext: 'Entrepreneurial, articulate, polite, and forward-looking. Nairobi tech-hub energy with East African clarity.',
    antiPatterns: ['Standard American English', 'British RP English', 'West African Pidgin'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'GA': {
    countryId: 'GA',
    region: 'Central Africa',
    capital: 'Libreville',
    localLanguages: ['Fang', 'Myene', 'Nzebi'],
    speechMelody: 'Smooth, relaxed, refined, and sophisticated. Controlled pitch contour with subtle equatorial elegance.',
    consonantStyle: 'Soft, rounded Bantu-influenced consonant articulation with polished, open French vowels.',
    rhythmPattern: 'Fluid, unhurried, and continuous pacing where sentences flow effortlessly without abrupt stops.',
    culturalContext: 'Calm, cultivated, diplomatic, and noble. Reflects equatorial forest heritage and Libreville refinement.',
    antiPatterns: ['Parisian French', 'Canadian French', 'Belgian French', 'Harsh European French'],
    defaultWarmth: 7,
    defaultConfidence: 8,
    defaultEnergy: 6
  },
  'BJ': {
    countryId: 'BJ',
    region: 'West Africa',
    capital: 'Cotonou',
    localLanguages: ['Fon', 'Yoruba', 'Bariba'],
    speechMelody: 'Warm, resonant, narrative intonation shaped by Fon tonal pitch movements and expressive inflection.',
    consonantStyle: 'Deep, chesty consonant resonance with expansive, clear vowels and nasal harmony.',
    rhythmPattern: 'Deliberate, storytelling-oriented rhythm with meaningful artistic pauses.',
    culturalContext: 'Deeply traditional, respectful, spirited, and historical. Rooted in ancient Dahomey oral art.',
    antiPatterns: ['Parisian French', 'European French', 'Monotone delivery'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  'BF': {
    countryId: 'BF',
    region: 'West Africa',
    capital: 'Ouagadougou',
    localLanguages: ['Mooré', 'Dioula', 'Fulfulde'],
    speechMelody: 'Grounded, sincere, steady pitch contour conveying deep honesty, integrity, and direct connection.',
    consonantStyle: 'Strong, clear, unpretentious consonants derived from Mooré phonetic strength.',
    rhythmPattern: 'Even, march-like steady rhythm paced deliberately for absolute understanding.',
    culturalContext: 'Proud, earnest, and deeply sincere — representing the "Land of Upright People".',
    antiPatterns: ['Parisian French', 'Overly dramatic speech', 'Rushed urban French'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 7
  },
  'ML': {
    countryId: 'ML',
    region: 'West Africa',
    capital: 'Bamako',
    localLanguages: ['Bambara', 'Songhai', 'Tamasheq'],
    speechMelody: 'Poetic, flowing, deeply musical Griot melody. Intonation ebbs and flows like ancestral storytelling.',
    consonantStyle: 'Softened, melodious consonants with rich Bambara vowel lilt and warm resonance.',
    rhythmPattern: 'Fluid, cascading cadence structured like musical storytelling phrases.',
    culturalContext: 'Reverent, historic, artistic, and peaceful. The voice is a noble instrument of wisdom and history.',
    antiPatterns: ['Parisian French', 'Harsh aggressive tones', 'Rapid staccato'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'TG': {
    countryId: 'TG',
    region: 'West Africa',
    capital: 'Lomé',
    localLanguages: ['Ewe', 'Kabiye'],
    speechMelody: 'Friendly, bright, inviting pitch modulation that shows high empathy and warmth.',
    consonantStyle: 'Clear, crisp consonants with distinct Ewe vowel coloring and gentle articulation.',
    rhythmPattern: 'Upbeat, bouncy, lively rhythm reflecting coastal warmth.',
    culturalContext: 'Welcoming, relaxed, communal, and genuine. Coastal Lomé warmth and community connection.',
    antiPatterns: ['Parisian French', 'Cold distant European tone'],
    defaultWarmth: 9,
    defaultConfidence: 7,
    defaultEnergy: 8
  },
  'CG': {
    countryId: 'CG',
    region: 'Central Africa',
    capital: 'Brazzaville',
    localLanguages: ['Kikongo', 'Lingala'],
    speechMelody: 'Sophisticated, stylized, and velvety smooth. Lingala musicality fused with elegant phrasing.',
    consonantStyle: 'Soft, rounded, impeccably stylized French pronunciation with Central African warmth.',
    rhythmPattern: 'Graceful, continuous cadence without harsh stops, moving with quiet pride.',
    culturalContext: 'Inspired by La Sape culture — impeccably polished, elegant, proud, and distinguished.',
    antiPatterns: ['Parisian French', 'Standard European French', 'Unrefined delivery'],
    defaultWarmth: 7,
    defaultConfidence: 9,
    defaultEnergy: 7
  },
  'TN': {
    countryId: 'TN',
    region: 'North Africa',
    capital: 'Tunis',
    localLanguages: ['Tunisian Derja'],
    speechMelody: 'Bright, agile, Mediterranean melody. Quick pitch inflections blending Derja and French cadences.',
    consonantStyle: 'Crisp, forward consonants with smoothed guttural sounds and clear open vowels.',
    rhythmPattern: 'Rapid, energetic, staccato rhythm filled with expressive Mediterranean vitality.',
    culturalContext: 'Cosmopolitan, warm, scholarly, and vibrant Mediterranean North African voice.',
    antiPatterns: ['Parisian French', 'Gulf Arabic', 'Levantine Arabic'],
    defaultWarmth: 8,
    defaultConfidence: 8,
    defaultEnergy: 9
  },
  'DZ': {
    countryId: 'DZ',
    region: 'North Africa',
    capital: 'Alger',
    localLanguages: ['Darja', 'Tamazight'],
    speechMelody: 'Bold, assertive, passionate intonation with strong emphasis and decisive pitch drops at sentence ends.',
    consonantStyle: 'Heavy, guttural Arabic consonant depth (kh, q) infusing French words with authentic Maghrebi power.',
    rhythmPattern: 'Punctuated, rhythmic bursts of passionate delivery followed by intentional dramatic pauses.',
    culturalContext: 'Fiery, proud, independent, and commanding. A voice of dignity and strength.',
    antiPatterns: ['Parisian French', 'Timid weak delivery', 'Middle Eastern Arabic'],
    defaultWarmth: 6,
    defaultConfidence: 10,
    defaultEnergy: 9
  },
  'EG': {
    countryId: 'EG',
    region: 'North Africa',
    capital: 'Le Caire',
    localLanguages: ['Egyptian Arabic'],
    speechMelody: 'Theatrical, warm, iconic Cairo melody. Richly expressive pitch drawl recognized across the region.',
    consonantStyle: 'Hard "g" for "j", elongated vowels, broad, relaxed, cinematic articulation.',
    rhythmPattern: 'Flowing, rhythmic, engaging, and cinematic with natural dramatic pauses.',
    culturalContext: 'Charming, dramatic, master-storyteller energy rooted in Egyptian film and broadcast legacy.',
    antiPatterns: ['Standard American English', 'Levantine Arabic', 'Gulf Arabic'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 8
  },
  'UG': {
    countryId: 'UG',
    region: 'East Africa',
    capital: 'Kampala',
    localLanguages: ['Luganda', 'Swahili', 'Runyankore'],
    speechMelody: 'Gentle, sing-song Luganda melody. Soft pitch modulation carrying profound warmth.',
    consonantStyle: 'Soft consonants avoiding harsh plosives, paired with extended, melodic vowels.',
    rhythmPattern: 'Smooth, unhurried, continuous flow with gentle transitions between phrases.',
    culturalContext: 'Pearl of Africa identity — famed for extreme politeness, warmth, and respectful grace.',
    antiPatterns: ['Standard American English', 'British RP English', 'Aggressive delivery'],
    defaultWarmth: 10,
    defaultConfidence: 7,
    defaultEnergy: 6
  },
  'TZ': {
    countryId: 'TZ',
    region: 'East Africa',
    capital: 'Dar es Salaam',
    localLanguages: ['Swahili'],
    speechMelody: 'Deeply resonant, pure Swahili rolling melody. Peaceful, grounded, and harmonious pitch contour.',
    consonantStyle: 'Clean, soft Bantu articulation with unblemished, pure open vowels.',
    rhythmPattern: 'Relaxed, steady, rhythmic coastal cadence (Bongo Flava peace and tranquility).',
    culturalContext: 'Peaceful, unified, harmonious Swahili identity — warm, inclusive, and grounded.',
    antiPatterns: ['Standard American English', 'British RP English', 'Rushed stressful cadence'],
    defaultWarmth: 9,
    defaultConfidence: 8,
    defaultEnergy: 7
  }
};

